# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Graham Rush"                                # Your name
  description: "Graham Rush. Lecturer at Leeds Beckett University."   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/sea-ice.png
  
  reader-mode: true # if you’d like users to be able to hide the side navigation and table of contents and have a more focused reading experience, you can enabled reader-mode. When enabled, a reader-mode toggle will appear on the navbar, if present, or on the sidebar. When pressed, the toggle will ‘roll up’ the sidebar and table of contents.
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: FALSE
    logo: /img/sea-ice.png
    
    # your sub-pages
    left:
      - text: "Research"
        href: projects/index.qmd
      # - text: "Photography"
      #   href: photography/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Publications"
        href: articles/index.qmd
      - text: "Experience"
        href: interests/index.qmd
      # - text: "CV"
      #   href: cv/index.qmd
      # - text: "Slideshow"
      #   href: slideshow/index.qmd
        
    
    # your social media handles
    right:
      # - icon: folder-symlink
      #   href: https://www.marvinschmitt.com/blog/website-tutorial-quarto/
      # - text: '<i class="fas fa-link"></i> Link Text'
      #   href: https://www.marvinschmitt.com/blog/website-tutorial-quarto/
      - icon: twitter
        href: https://twitter.com/goatyrush
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/marvin-schmitt-a85b321a2/
      - icon: envelope
        aria-label: email
        href: "mailto:g.rush@leedsbeckett.ac.uk"
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Graham Rush CC BY-SA 4.0</span>
    center: |
    right: |
      <span class="faux-block"> Built with [Quarto](https://quarto.org/) and [RStudio](https://posit.co/products/open-source/rstudio/) </span>
  sidebar:
    style: "docked" # or "docked", "floating"
    search: false
    contents:
      - section: "Menu"
        contents:
          - text: "Research"
            href: projects/index.qmd
          - text: "Teaching"
            href: teaching/index.qmd
          - text: "Publications"
            href: articles/index.qmd
          - text: "Experience"
            href: interests/index.qmd
          # - text: "Slideshow"
          #   href: slideshow/index.qmd
  # add page navigation
  page-navigation: true
  
project:
  type: website
  output-dir: docs

  preview: 
    port: 443
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - minty
      - html/styles.scss
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    link-external-newwindow: true # this opens any links in a new tab
    
